// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/companies/internal/domain/interceptors (interfaces: CompanyInterceptor)

// Package mock_interceptors is a generated GoMock package.
package mock_interceptors

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/companies/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockCompanyInterceptor is a mock of CompanyInterceptor interface.
type MockCompanyInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyInterceptorMockRecorder
}

// MockCompanyInterceptorMockRecorder is the mock recorder for MockCompanyInterceptor.
type MockCompanyInterceptorMockRecorder struct {
	mock *MockCompanyInterceptor
}

// NewMockCompanyInterceptor creates a new mock instance.
func NewMockCompanyInterceptor(ctrl *gomock.Controller) *MockCompanyInterceptor {
	mock := &MockCompanyInterceptor{ctrl: ctrl}
	mock.recorder = &MockCompanyInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyInterceptor) EXPECT() *MockCompanyInterceptorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyInterceptor) Create(arg0 context.Context, arg1 *models.CompanyCreate, arg2 *models.Token) (*models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCompanyInterceptorMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyInterceptor)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockCompanyInterceptor) Delete(arg0 context.Context, arg1 models.UUID, arg2 *models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyInterceptorMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyInterceptor)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockCompanyInterceptor) Get(arg0 context.Context, arg1 models.UUID, arg2 *models.Token) (*models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompanyInterceptorMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyInterceptor)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockCompanyInterceptor) List(arg0 context.Context, arg1 *models.CompanyFilter, arg2 *models.Token) ([]*models.Company, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Company)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCompanyInterceptorMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCompanyInterceptor)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockCompanyInterceptor) Update(arg0 context.Context, arg1 *models.CompanyUpdate, arg2 *models.Token) (*models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCompanyInterceptorMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCompanyInterceptor)(nil).Update), arg0, arg1, arg2)
}
