version: 3
tasks:
  build:
    env:
      CGO_ENABLED: 1
    cmds:
      - go build -ldflags "-X github.com/018bf/companies.Version={{ .version }}" -v -o ./dist/companies ./cmd/companies
    vars:
      version:
        sh: git describe --tags --abbrev=0

  test:
    vars:
      mode: '{{ default "" .mode }}'
      count: '{{ default "1" .count }}'
    env:
      COMPANIES_CONFIG_PATH: "{{.USER_WORKING_DIR}}/configs/test.toml"
    cmds:
      - go test {{ .mode }} -test.count {{ .count }} -cover ./... -coverprofile ./coverage.out -coverpkg ./...
      - defer: rm ./coverage.out
      - go tool cover -func ./coverage.out

  unit:
    cmds:
      - task: test
        vars:
          mode: "-short"
          count: "50"
  lint:
    cmds:
      - golangci-lint run ./... --timeout 5m0s

  clean:
    cmds:
      - golangci-lint run ./... --fix

  log:
    cmds:
      - git-chglog --config docs/.chglog/config.yml --output docs/CHANGELOG.md --next-tag {{ .tag }}

  release:
    deps:
      - task: lint
      - task: unit
    cmds:
      - git flow release start {{ .tag }}
      - task: log
      - git add .
      - git commit -m "bumped the version number"
      - git flow release finish {{ .tag }} -f docs/CHANGELOG.md -p --showcommands
