// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/018bf/companies/internal/domain/usecases (interfaces: CompanyUseCase)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	models "github.com/018bf/companies/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockCompanyUseCase is a mock of CompanyUseCase interface.
type MockCompanyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyUseCaseMockRecorder
}

// MockCompanyUseCaseMockRecorder is the mock recorder for MockCompanyUseCase.
type MockCompanyUseCaseMockRecorder struct {
	mock *MockCompanyUseCase
}

// NewMockCompanyUseCase creates a new mock instance.
func NewMockCompanyUseCase(ctrl *gomock.Controller) *MockCompanyUseCase {
	mock := &MockCompanyUseCase{ctrl: ctrl}
	mock.recorder = &MockCompanyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyUseCase) EXPECT() *MockCompanyUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyUseCase) Create(arg0 context.Context, arg1 *models.CompanyCreate) (*models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCompanyUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockCompanyUseCase) Delete(arg0 context.Context, arg1 models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyUseCaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyUseCase)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockCompanyUseCase) Get(arg0 context.Context, arg1 models.UUID) (*models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompanyUseCaseMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyUseCase)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockCompanyUseCase) List(arg0 context.Context, arg1 *models.CompanyFilter) ([]*models.Company, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*models.Company)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCompanyUseCaseMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCompanyUseCase)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockCompanyUseCase) Update(arg0 context.Context, arg1 *models.CompanyUpdate) (*models.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*models.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCompanyUseCaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCompanyUseCase)(nil).Update), arg0, arg1)
}
