apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "companies.fullname" . }}
  labels:
  {{- include "companies.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote  }}
