apiVersion: v1
kind: Secret
metadata:
  name: {{ include "companies.fullname" . }}
  labels:
  {{- include "companies.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URI: {{ .Values.database.uri | b64enc | quote  }}
  AUTH_PUBLIC_KEY: {{ .Values.auth.publicKey | b64enc | quote  }}
  AUTH_PRIVATE_KEY: {{ .Values.auth.privateKey | b64enc | quote  }}
  AUTH_REFRESH_TTL: {{ .Values.auth.refreshTTL | b64enc | quote  }}
  AUTH_ACCESS_TTL: {{ .Values.auth.accessTTL | b64enc | quote  }}
